"""single_container_migration

Revision ID: 6a26ec39bb13
Revises: 001
Create Date: 2026-08-01 11:39:16.167643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a26ec39bb13'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'source', 'query', name='uq_listing_query')
    )
    op.create_index(op.f('ix_listing_queries_listing_id'), 'listing_queries', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_queries_source'), 'listing_queries', ['source'], unique=False)
    op.add_column('listing_snapshots', sa.Column('schema_version', sa.Integer(), nullable=False))
    op.add_column('listing_snapshots', sa.Column('payload_hash', sa.String(), nullable=False))
    op.add_column('listing_snapshots', sa.Column('image_urls_json', sa.Text(), nullable=False))
    op.create_index(op.f('ix_listing_snapshots_payload_hash'), 'listing_snapshots', ['payload_hash'], unique=False)
    op.drop_column('listing_snapshots', 'image_url')
    op.add_column('listings', sa.Column('image_urls_json', sa.Text(), nullable=False))
    op.add_column('listings', sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('listings', sa.Column('inactive_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('listings', sa.Column('reactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('listings', sa.Column('consecutive_misses', sa.Integer(), nullable=False))
    op.add_column('notifications', sa.Column('event_key', sa.String(), nullable=False))
    op.create_index(op.f('ix_notifications_event_key'), 'notifications', ['event_key'], unique=True)
    op.add_column('part_matches', sa.Column('compatibility_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('part_matches', 'compatibility_status')
    op.drop_index(op.f('ix_notifications_event_key'), table_name='notifications')
    op.drop_column('notifications', 'event_key')
    op.drop_column('listings', 'consecutive_misses')
    op.drop_column('listings', 'reactivated_at')
    op.drop_column('listings', 'inactive_at')
    op.drop_column('listings', 'last_changed_at')
    op.drop_column('listings', 'image_urls_json')
    op.add_column('listing_snapshots', sa.Column('image_url', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_listing_snapshots_payload_hash'), table_name='listing_snapshots')
    op.drop_column('listing_snapshots', 'image_urls_json')
    op.drop_column('listing_snapshots', 'payload_hash')
    op.drop_column('listing_snapshots', 'schema_version')
    op.drop_index(op.f('ix_listing_queries_source'), table_name='listing_queries')
    op.drop_index(op.f('ix_listing_queries_listing_id'), table_name='listing_queries')
    op.drop_table('listing_queries')
    # ### end Alembic commands ###
