sscom:
  feeds:
    - https://www.ss.com/lv/transport/spare-parts/opel/signum/rss/
    - https://www.ss.com/lv/transport/spare-parts/opel/vectra/rss/
    - https://www.ss.com/lv/transport/cars/opel/signum/rss/
    - https://www.ss.com/lv/transport/cars/opel/vectra/rss/
